### ISSUE TITLE
Adding CLI Support

### ISSUE THREAD

**Issue by nvx0** [jagt/clumsy#104]
It would be greate if Clumsy would have a CLI. Thanks

**Comment by SleepyBag** [comment]
@jagt How do you think about this? I can help contribute to this if you are interested in merging it.

**Comment by jagt** [comment]
Hi. I'm not using clumsy actively so the project is mostly in maintenance for now.

> @jagt How do you think about this? I can help contribute to this if you are interested in merging it.

I'll suggest to go for building a separate exe for the cli, for example `clumsy-cmd.exe`. For the CLI it can only start with fixed parameters and ctrl-c to quit globally. In this way it should have minimal code changes especially on the UI stuff.

Cheers.

**Comment by nvx0** [comment]
Cool, that would be appreciated.
