### ISSUE TITLE
command line interface?

### ISSUE THREAD

**Issue by BambiMC** [jagt/clumsy#115]
Is it possible to use clumsy in an automated manner?
Through command line maybe?
What would be the syntax for that?

Thanks a lot in advance!

**Comment by apal0934** [comment]
Hopefully you already found them, but some of the arguments are listed here: https://github.com/jagt/clumsy/wiki/Command-Line-Arguments

Some arguments are missing from the list, I can't remember all of them off the top of my head but the most noticeable is `--throttle-frame [0-1000]`

**Comment by BambiMC** [comment]
Thanks a lot for the help!
Kinda overlooked that part ^^
