### ISSUE TITLE
failed to open device (code:1783)

### ISSUE THREAD

**Issue by levenies** [jagt/clumsy#116]
![image](https://user-images.githubusercontent.com/28750545/183552604-87e82f77-ebc0-40bb-a0ed-32ebdb3e9072.png)
How to solve this problem?

The program opened by the administrator also reports the above error

**Comment by BambiMC** [comment]
May be a stupid question.
Have you opened the program as admin?

**Comment by levenies** [comment]
> May be a stupid question. Have you opened the program as admin?

Of course, it is opened by the administrator

**Comment by levenies** [comment]
The problem is solved. I turned on the anti-virus software. After closing it, it can run normally
