### ISSUE TITLE
Failed to start filtering: failed to open device (code:1326)

### ISSUE THREAD

**Issue by nsparisi** [jagt/clumsy#137]
Clumsy 0.3 and 0.2 stopped working for me on windows 10. Last time I tested was back in February '23, the same executables were working successfully. Full error is:

> Failed to start filtering: failed to open device (code:1326)
> Make sure you run clumsy as Administrator.

In EventViewer there is an error:

> The WinDivert service failed to start due to the following error: 
> The user name or password is incorrect.

I did some research and tried Restarting + Shutting Down my pc, but still no luck.

**Comment by nsparisi** [comment]
I have solved the issue. The WinDivert service was trying to start, and the path specified in the registry (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert) was pointing to an invalid location. More specifically for my case, the clumsy folder location was on a network share, and for some reason windows didn't like that. 

To fix: I deleted the registry directory WinDivert, then rebooted windows and moved the clumsy.exe folder to my local drive. After running as administrator, clumsy.exe was working again. 

In EventViewer I can see:

> A service was installed in the system.
> 
> Service Name:  WinDivert
> Service File Name:  C:\tools\clumsy\WinDivert64.sys
> Service Type:  kernel mode driver
> Service Start Type:  demand start
> Service Account:

**Comment by jasensic** [comment]
> I have solved the issue. The WinDivert service was trying to start, and the path specified in the registry (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDivert) was pointing to an invalid location. More specifically for my case, the clumsy folder location was on a network share, and for some reason windows didn't like that.
> 
> To fix: I deleted the registry directory WinDivert, then rebooted windows and moved the clumsy.exe folder to my local drive. After running as administrator, clumsy.exe was working again.

It has solved my problem too: failed to open device (code:2)
