### ISSUE TITLE
Compatibility issue with Windows Server 2008?

### ISSUE THREAD

**Issue by bigplant** [jagt/clumsy#14]
Clumsy 0.2 starts up the program fine with Windows Server 2008. However, whenever I press the Start button, it will produce the error message: 'Failed to start filtering : failed to open device (code:127). Make sure you run clumsy as Administrator'.

This occurs when I use the default localhost ipv4 all preset ('outbound and ip.DstAddr >= 127.0.0.1 and ip.DstAddr <= 127.255.255.255'). It also happens with the other presets. If I leave the filtering textbox blank, it will give a 'Failed to start filtering : filter syntax error.' error message instead.

This message occurs on both 32 and 64 bit operating systems. I'm running the program with an administrator account, and I've right-clicked on the executable and selected 'Run as administrator'. The program runs correctly on Windows 7 though.

**Comment by bigplant** [comment]
Awesome, that's fixed the issue. I was using 2008 SP1. Thanks for your help

**Comment by ianbannerman** [comment]
Awesome! Glad to hear it's working :)

**Comment by jagt** [comment]
@ianbannerman Thanks! I'll add this to the FAQ.
