### ISSUE TITLE
Emulate packet burst losses

### ISSUE THREAD

**Issue by marcojrfurtado** [jagt/clumsy#20]
It would be nice to have an option to emulate packet burst losses when we use the "Drop" method.
Maybe there could be something similar to the "Correlation" parameter from WANem (The Wide Area Network Emulator). Their correlation is documented as follows:

![wanem_correlation](https://cloud.githubusercontent.com/assets/450298/8435596/650920ca-1f0f-11e5-89d9-64d677d3895b.PNG)

**Comment by jagt** [comment]
I've added a drop toggled checkbox for throttle. Obviously it doesn't follow the equation you've posted... You can try it out to see if it works.  

You can get the prerelease here: `https://github.com/jagt/clumsy/releases/tag/0.3rc1`

**Comment by marcojrfurtado** [comment]
Thanks jagt,
Seems to be working, closing issue
