### ISSUE TITLE
port filter not working on windows

### ISSUE THREAD

**Issue by lukyer** [jagt/clumsy#21]
ip.DstPort == 12354 or ip.SrcPort == 12354 is not valid (default rule)
tcp.DstPort nor tcp.SrcPort is working (however valid rule)

Host machine: Windows 8 64b, version clumsy: 0.2 64b

**Comment by raybooysen** [comment]
+1.

The default rules when selected don't work

**Comment by jagt** [comment]
Hi, this is a mistake.. It's now fixed and I'll do a release maybe next week.
