### ISSUE TITLE
Failed to start filtering: failed to open device (code:1753)

### ISSUE THREAD

**Issue by r1me** [jagt/clumsy#24]
Clumsy isn't able to start filtering, gives an error: 
Failed to start filtering: failed to open device (code:1753)

Windows 7 x64
NIC: Realtek PCIe GBE Family Controller (on board), no other network cards
COMODO Firewall (latest)
It is a physical PC, not VM.

I run Clumsy from unpacked clumsy-0.2-win64.zip, of course i do have admin privileges.
![clumsyerror](https://cloud.githubusercontent.com/assets/13695767/9703931/1f9f5bbc-5493-11e5-9325-3fd4ef8a3916.png)

**Comment by r1me** [comment]
Ok, after research i understood Divert requires Base Filtering Engine service to be running, that i had turned off. Now it's all good.

**Comment by jagt** [comment]
Thanks for the heads up! I'll update the manual :)
