### ISSUE TITLE
Included IUP library is outdated

### ISSUE THREAD

**Issue by arcanelab** [jagt/clumsy#25]
The included IUP library is outdated (3.8), it does not handle HiDPI-supporting applications. The newest version (3.16) includes HiDPI support.

Sidenote: to make clumsy HiDPI compatible, call `SetProcessDpiAwareness(PROCESS_SYSTEM_DPI_AWARE);` from `main()`.

**Comment by jagt** [comment]
Thanks for the info. I'll upgrade IUP on the next release..

**Comment by jagt** [comment]
I just noticed that IUP 3.16 release is missing MinGW 64 libraries. I'll have to wait for it to upgrade.
