### ISSUE TITLE
Is it possible to simulate latency and bandwidth throughput?

### ISSUE THREAD

**Issue by jwillmer** [jagt/clumsy#29]
I need to simulate a satelite connection that includes latencys of 2-3 seconds and a fixed (max) bandwidth. Is this possible with the tool?

**Comment by celeron533** [comment]
@jwillmer , I believe the "Lag" option meets your requirement.

**Comment by jwillmer** [comment]
ah, sorry. Of course I can use the lag-option but what about bandwidth throughput? The throttle-option only blocks the traffic but does not create a bottleneck.

**Comment by CA4GitHub** [comment]
@jwillmer did you find a way to control bandwidth throughput?

**Comment by ianbannerman** [comment]
I did so with Inssidious -- lagged each packet for a minimum of some time whatever the max throughput would be for that connection style. You can grab / reimplement that code if you'd like. https://github.com/ianbannerman/Inssidious/blob/master/InssidiousCore/TamperModules/TamperSpeed.cpp

Speeds are defined here: https://github.com/ianbannerman/Inssidious/blob/master/InssidiousCore/TamperTypes.h

**Comment by jagt** [comment]
@CA4GitHub not yet :(
@ianbannerman I've tried that approach but seems it didn't work as expected, and I can't get an accurate result. Thanks for the info, I'll try to look into it.

**Comment by jwillmer** [comment]
I am using the [Network Emulator Toolkit](https://blog.mrpol.nl/2010/01/14/network-emulator-toolkit/). It works like a charm :+1: 
Tutorial on YouTube: [Network Emulator For Windows Toolkit Tutorial](https://www.youtube.com/watch?v=s5o_GnYOloA)

**Comment by ianbannerman** [comment]
@jagt for sure, let me know if I can help at all. I definitely built off of your work with Clumsy, Inssidious would not exist as it is without it. Thank you!
