### ISSUE TITLE
Increase maximum latency beyond 3000ms

### ISSUE THREAD

**Issue by 1kastner** [jagt/clumsy#36]
Is there any specific reason why you cut the latency at 3000ms? I would like to rather have a latency of 20 seconds. Could I easily change it or did you face problems before when you tried that?

**Comment by jagt** [comment]
Actually it's an arbitrary value. You can download the source and change the value as you like, or you can wait for a next release which might not happen soon.... Please refer to the manual for build instructions :)

**Comment by celeron533** [comment]
or just create a pull request :blush:

> Actually it's an arbitrary value. You can download the source and change the value as you like, or you can wait for a next release which might not happen soon.... Please refer to the manual for build instructions

**Comment by 1kastner** [comment]
The change was pretty easy, one line, one additional 0 did the job for me. But I can not any build instructions ( http://jagt.github.io/clumsy/manual.html ) or any of the official websites.

**Comment by jagt** [comment]
@1kastner it's on this page:  http://jagt.github.io/clumsy/download.html :)

**Comment by 1kastner** [comment]
Thanks for the support, if you happen to release it officially at some point, let me know :)

**Comment by cfcubed** [comment]
Posted on other request for this:  Old request but...  Stumbled upon clumsy looking for quick/easy TCP/IP socket latency inject.  Wanted higher than 3000ms lag and, keeping with the quick/easy, used a HEX editor to locate 3000 (string) in clumsy.exe (lag.c's DEFINE) and changed it to 9999 (string) then saved.  Worked fine for my use, increased lag max to 9999ms which was enough for the task.

**Comment by jagt** [comment]
I'll increase the limit in the next release. Never thought that one would want lag that high.

**Comment by 1kastner** [comment]
@jagt for satellite internet communication such high lacks might occur depending on orbit of the satellite, weather, etc. and this tool is one of the chances to simulate it.

**Comment by NitricAcidDev** [comment]
how do i change the limit
