### ISSUE TITLE
Preset: all ipv4 against port, results in "Failed to start filtering : filter syntax error"

### ISSUE THREAD

**Issue by siNSTR** [jagt/clumsy#44]
When I attempt to use the preset "all ipv4 against port" the syntax cannot be verified and fails. 

![image](https://cloud.githubusercontent.com/assets/12600722/24817912/69c0f02a-1bac-11e7-9911-930c8dc0263c.png)

**Comment by jagt** [comment]
Hi this is fixed in https://github.com/jagt/clumsy/issues/12
Next release should have this fix bundled.
