### ISSUE TITLE
RFE: Request to increase the Throttle and Lag values to 10,000ms (10sec) or higher

### ISSUE THREAD

**Issue by IanFright** [jagt/clumsy#55]
While 1000ms is a significant amount of time., there are senarios where is could be higher.

**Comment by cfcubed** [comment]
Old request but...  Stumbled upon clumsy looking for quick/easy TCP/IP socket latency inject.  Wanted higher than 3000ms lag and, keeping with the quick/easy, used a HEX editor to locate 3000 (string) in clumsy.exe (lag.c's DEFINE) and changed it to 9999 (string) then saved.  Worked fine for my use, increased lag max to 9999ms which was enough for the task.
