### ISSUE TITLE
Inbound not working "all receiving packets" after rebuilding 0.3rc3  

### ISSUE THREAD

**Issue by Tester47c** [jagt/clumsy#90]
after I rebuild 0.3rc3  the inbound "all receiving packets" dont work properly, but the inbound from the 0.3rc3 latest release works smoothly, I was wondering why when I build 0.3rc3 the inbound doesn't work?

**Comment by jagt** [comment]
Hi, can you try our builds here at: <https://github.com/jagt/clumsy/releases/tag/0.3rc3> and see if it works?

I just tried the 'All Receiving Packets' preset and it's working on my box.

**Comment by Tester47c** [comment]
> Hi, can you try our builds here at: https://github.com/jagt/clumsy/releases/tag/0.3rc3 and see if it works?
> 
> I just tried the 'All Receiving Packets' preset and it's working on my box.

Do I have to use msys2 to build properly? or could I use vsCMD? because I built it just fine with out msys2 so maybe that's the issue?

**Comment by jagt** [comment]
VS2019 should be working. Can you try use genie and follow the instructions here: http://jagt.github.io/clumsy/download.html

Make sure you start clumsy with administrator on. There's an auto detection but I'm not sure if it's broken atm.

**Comment by Tester47c** [comment]
> VS2019 should be working. Can you try use genie and follow the instructions here: http://jagt.github.io/clumsy/download.html
> 
> Make sure you start clumsy with administrator on. There's an auto detection but I'm not sure if it's broken atm.

Hi again, So I built it just fine with Genie & msys2 the build instructions you provided, and still inbound isn't working, how previous versions of clumsy worked, the inbound would freeze the p2p application I'm testing it on, through my Ethernet adapter, (0.3rc3 64bit official release) works well with inbound no issues, but when I Rebuild Clumsy 0.3rc3 the inbound doesn't seem to work with my Ethernet Adapter, so maybe it's a adapter issue? I just don't understand what the Stock version of clumsy 0.3rc3 exe (official release) has that My rebuild doesn't have.

**Comment by HawkTester** [comment]
> > VS2019 should be working. Can you try use genie and follow the instructions here: http://jagt.github.io/clumsy/download.html
> > Make sure you start clumsy with administrator on. There's an auto detection but I'm not sure if it's broken atm.
> 
> _UPDATE_ i got it to work turns out i just had to add the preset configuration in the coding, thanks

Hey, I was wondering if you could tell me what you did to make the inbound work I’ve been having trouble as well.

**Comment by jagt** [comment]
@HawkTester I tested it a bit on my box and seems it's working. Are you using the releases from here: <https://github.com/jagt/clumsy/releases/tag/0.3rc3>

**Comment by HawkTester** [comment]
> @HawkTester I tested it a bit on my box and seems it's working. Are you using the releases from here: <https://github.com/jagt/clumsy/releases/tag/0.3rc3>

The releases work, I'm just trying to build clumsy0.3 rc3 and the presets don't work.

**Comment by Tester47c** [comment]
> > @HawkTester I tested it a bit on my box and seems it's working. Are you using the releases from here: https://github.com/jagt/clumsy/releases/tag/0.3rc3
> 
> The releases work, I'm just trying to build clumsy0.3 rc3 and the presets don't work.

The presets works fine just add the preset configurations manually with the latest build steps everything works 100% smoothly

**Comment by Tester47c** [comment]
> > @HawkTester I tested it a bit on my box and seems it's working. Are you using the releases from here: https://github.com/jagt/clumsy/releases/tag/0.3rc3
> 
> The releases work, I'm just trying to build clumsy0.3 rc3 and the presets don't work.

or if you don't have experience just wait for the next release (:

**Comment by jagt** [comment]
Can you try this: <https://github.com/basil00/WinDivertTool>

And uninstall all windivert. Then run the latest release?

**Comment by Tester47c** [comment]
> Can you try this: https://github.com/basil00/WinDivertTool
> 
> And uninstall all windivert. Then run the latest release?

@HawkTester yes you can try this as well, for me I just needed to add the custom configurations in manually and inbound worked great. @jagt feel free to close this issue.

**Comment by HawkTester** [comment]
> > Can you try this: https://github.com/basil00/WinDivertTool
> 
> > 
> 
> > And uninstall all windivert. Then run the latest release?
> 
> 
> 
> @HawkTester yes you can try this as well, for me I just needed to add the custom configurations in manually and inbound worked great. @jagt feel free to close this issue. 

Yes I added custom configurations in thank you.
