### ISSUE TITLE
Where in (Main.c) do i Resize and Change Color of ui 

### ISSUE THREAD

**Issue by Student1094** [jagt/clumsy#91]
i rather have a black and white (dark mode) on the ui, suites my eyes better and looks more modern, I was browsing through main.c and couldn't find nothing can you Show a picture of where Color change can take place in the ui, same with "SIZE"
i am Still Learning, thanks.

**Comment by jagt** [comment]
Hi, UI is using [iup](https://www.tecgraf.puc-rio.br/iup/). You can reference docs there.
